language: android

jdk:
    - oraclejdk8

android:
    components:
        - platform-tools
        - tools
        - build-tools-23.0.2
        - android-22
        - extra-android-m2repository
        - extra-google-m2repository
    licenses:
        - android-sdk-license-.+

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/

script: ./gradlew assembleRelease


deploy:
    provider: releases
    api_key: "23f47492689c60131f7a0aee17c5f81027827a63"
    file: "$HOME/app/build/outputs/app-release.apk"
    skip_cleanup: true
